### POST to /example
POST http://localhost:3000/example
Content-Type: application/json

{
  "email": "alan.ramalho@gmail.com"
}

### GET to /example
GET http://localhost:3000/example
Content-Type: application/json

### GET to /example/:id
GET http://localhost:3000/example/4
Content-Type: application/json


### DEL to /example/all
DELETE http://localhost:3000/example/all
Content-Type: application/json
